#!/usr/bin/env python3
"""Shared machinery for this addon's generated stand-in models (tools/make_*.py).

Every model is a set of axis-aligned boxes. Conventions match the base mod's own sample pack:
+Z is forward, +Y is up, y=0 is the ground plane, one unit = one block.

Every box gets:
  - "g <name>" so the base mod's OBJ parser can drive it as a named part;
  - "vt" so each part samples a distinct colour column of a tiny palette PNG (the parser resolves
    vt by index, so the lines must be emitted - position-only faces would all sample (0,0));
  - "vn" per face, since the parser otherwise defaults every normal to straight up and the model
    would shade flat.

Each vehicle's texture is the same 16x16 palette layout with its own colours, so one Obj class
serves every model: box(..., "hull", ...) always samples column 0, whatever colour that is.
"""
import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1] / "src/main/resources/assets/humanoidrobotaddon"

# Palette: column index -> RGB. The texture is 16 wide; each colour fills one full-height column
# so a UV lookup only has to pick its u.
PALETTE = {
    "hull":    (96, 104, 112),    # 0 dark steel
    "panel":   (150, 160, 170),   # 1 light panel
    "joint":   (48, 48, 52),      # 2 near-black joints
    "accent":  (200, 70, 40),     # 3 red accent
    "visor":   (60, 220, 200),    # 4 cyan visor
    "gun":     (36, 36, 40),      # 5 gunmetal
    "pod":     (120, 110, 70),    # 6 olive missile pod
    "foot":    (70, 70, 74),      # 7
}
COLUMNS = list(PALETTE)


class Obj:
    def __init__(self, title, script="tools/make_sample_walker.py"):
        self.lines = [f"# {title} - humanoidrobotaddon sample (generated by {script})", ""]
        self.n_v = 0
        # One vt per palette column, one vn per axis direction, emitted up front.
        for i, name in enumerate(COLUMNS):
            u = (i + 0.5) / 16.0
            self.lines.append(f"vt {u:.6f} 0.500000")
        self.normals = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]
        for nx, ny, nz in self.normals:
            self.lines.append(f"vn {nx} {ny} {nz}")
        self.lines.append("")
        self.current_group = None

    def group(self, name):
        if name != self.current_group:
            self.lines.append(f"g {name}")
            self.current_group = name

    def box(self, group, colour, cx, cy, cz, sx, sy, sz):
        self.group(group)
        vt = COLUMNS.index(colour) + 1
        hx, hy, hz = sx / 2, sy / 2, sz / 2
        corners = [
            (cx - hx, cy - hy, cz - hz), (cx + hx, cy - hy, cz - hz),
            (cx + hx, cy + hy, cz - hz), (cx - hx, cy + hy, cz - hz),
            (cx - hx, cy - hy, cz + hz), (cx + hx, cy - hy, cz + hz),
            (cx + hx, cy + hy, cz + hz), (cx - hx, cy + hy, cz + hz),
        ]
        for x, y, z in corners:
            self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        b = self.n_v
        # (corner indices, normal index) - wound counter-clockwise seen from outside.
        faces = [
            ((1, 4, 3, 2), 6),  # -Z back
            ((5, 6, 7, 8), 5),  # +Z front
            ((1, 2, 6, 5), 4),  # -Y bottom
            ((2, 3, 7, 6), 1),  # +X
            ((3, 4, 8, 7), 3),  # +Y top
            ((4, 1, 5, 8), 2),  # -X
        ]
        for idx, vn in faces:
            self.lines.append("f " + " ".join(f"{b + i}/{vt}/{vn}" for i in idx))
        self.n_v += 8
        self.lines.append("")

    def write(self, path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(self.lines) + "\n", encoding="utf-8")
        print(f"wrote {path} ({self.n_v} vertices)")


def make_texture(path, overrides=None):
    """Writes the palette PNG. overrides: {colour name: (r, g, b)} to recolour a vehicle while
    keeping the column layout every Obj relies on."""
    colours = dict(PALETTE)
    colours.update(overrides or {})
    img = Image.new("RGBA", (16, 16), (255, 0, 255, 255))
    for i, name in enumerate(COLUMNS):
        r, g, b = colours[name]
        for y in range(16):
            img.putpixel((i, y), (r, g, b, 255))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)
    print(f"wrote {path}")





def wheel_x(obj, group, colour, cx, cy, cz, width, radius):
    """A road wheel / roller turning about the X axis: three overlapping boxes (a square and a
    cross) - reads as round at a glance, and its spin is visible because the profile isn't."""
    obj.box(group, colour, cx, cy, cz, width, radius * 1.4, radius * 1.4)
    obj.box(group, colour, cx, cy, cz, width * 0.98, radius * 2.0, radius * 0.9)
    obj.box(group, colour, cx, cy, cz, width * 0.98, radius * 0.9, radius * 2.0)
